### ISSUE TITLE
Need documentation on accessing RS-485 bus from pi

### ISSUE THREAD

**Issue by cmc0619** [SequentMicrosystems/megabas-rpi#1]
Can't figure out how (or if possible) to access RS-485 bus from raspberry pi as a device.

**Comment by alexburcea2877** [comment]
Hi,

It is possible to access RS-485 bus with the Raspberry USART port.
1) You need to update the board firmware, instructions here:
https://github.com/SequentMicrosystems/megabas-rpi/blob/master/update/README.md
2) Disable modbus communication  with command  "megabas 0 rs485wr 0 9600 1
0 1" , assuming that you already install the megabas command (
https://github.com/SequentMicrosystems/megabas-rpi/blob/master/README.md)
3) place 2 jumpers on the pindeader in the place marked with "RXD" and
"TXD" .
Now you can use any tool  or application to read and write data thru RS485.

Let me know if something is unclear.


În vin., 18 sept. 2020 la 20:20, cmc0619 <notifications@github.com> a scris:

**Comment by cmc0619** [comment]
I'm on the right track then!  I have done all this.  Does it appear as a device? Like a RS-485 USB dongle shows up as /dev/USB0.

**Comment by alexburcea2877** [comment]
No, is just connected to the Raspberry USART port (GPIO14, GPIO15), you
have to enable the USART  from the "raspi-config" and  use-it , some
reference you can find here:
https://www.electronicwings.com/raspberry-pi/raspberry-pi-uart-communication-using-python-and-c


În lun., 21 sept. 2020 la 23:13, cmc0619 <notifications@github.com> a scris:

**Comment by cmc0619** [comment]
I undestand now! Thanks!
