### ISSUE TITLE
Write fail during firmware update

### ISSUE THREAD

**Issue by ddyer8** [SequentMicrosystems/megabas-rpi#11]
I recently (~1 week ago) updated the firmware on the board but am having trouble using RS485 comm, so decided to try another firmware update.  Now I'm getting the following error:

pi@poolpi:~/megabas-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
We strongly recommend to disconnect all outputs from the board since they can change state unpredictably.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 190025000357415636313320
Downloading firmware...               Board version < 4.0
Done
Programming the board...  2%
Write fail!
FAIL to write!

I have gotten anywhere between 2% and 5% complete before failure.

Sometimes I also get:
read cmd NACK ret 0x00 !!!
Bootloader no answer!!!

**Comment by alexburcea2877** [comment]
Hi,
Make sure nobody tries to access the card during the update.

**Comment by ddyer8** [comment]
There are no connections to the card, but there are 2 other sequent boards and an Atlas Scientific whitebox T3 stacked on the pi. Do I need to unstack everything?

Thank you,
Dustin

**Comment by alexburcea2877** [comment]
Normally is not a problem to have more cards on the bus but is better to
remove them. Make sure no resident program on the raspberry pi try to
access I2C port during the update (NodeRED or running python or shell
scripts).

**Comment by ddyer8** [comment]
there were no issues with the cards on the stack.  I had a background process accessing the board.
