### ISSUE TITLE
Cannot read button

### ISSUE THREAD

**Issue by frasmarco** [SequentMicrosystems/megabas-rpi#16]
the command `megabas 0 btn` always return 0 even when the button is pushed.
Documentation doesn't mention the button at all.

`pi@pi:~ $ megabas 0 board
Firmware ver 02.00, CPU temperature 34 C, Power source 25.36 V, Raspberry 5.22 V`

**Comment by alexburcea2877** [comment]
Hi,
Please do a firmware update, you will find instructions in the readme.

**Comment by frasmarco** [comment]
It woks.

Many thanks
