### ISSUE TITLE
Codesys 

### ISSUE THREAD

**Issue by nikke344** [SequentMicrosystems/megabas-rpi#2]
Codesys package for this👌

**Comment by alexburcea2877** [comment]
Unfortunately we do not have Codesys library for megabas and is hard to give you a expectation time.
I can tell you that the OpenPLC and Node-Red driver will be available soon.

**Comment by nikke344** [comment]
hi i am modified the older library and it needs little adjustments. can i send it to you if you look the litle issues off there

**Comment by alexburcea2877** [comment]
Create a repo and we can both contribute on.
I will be happy to help.

**Comment by alexburcea2877** [comment]
I forget is a compressed package... send me the code and I will take a look.

**Comment by nikke344** [comment]
what is the best way o send it?

**Comment by alexburcea2877** [comment]
I guess you can attach file to the message or send me a direct email (olcitu@gmail.com)

**Comment by nikke344** [comment]
okay i send it to you

**Comment by alexburcea2877** [comment]
Thank you for your help in creating the library.

**Comment by alexburcea2877** [comment]
Hi,
Any chance that you might have the source code for the MEGA_BAS and 4-RELAYS codesys libraries that you made-it few years ago? I lost my copies. 
Thank you in advance.
Alex.
