### ISSUE TITLE
Modbus 

### ISSUE THREAD

**Issue by nikke344** [SequentMicrosystems/megabas-rpi#3]
Is It possible make this megabas to act like modbus bridge?

**Comment by alexburcea2877** [comment]
Can you be more specific? 
Give me a example of modbus bridge and a link to his documentation or explain to me what modbus bridge is.

**Comment by nikke344** [comment]
If jumpers are installed, Raspberry Pi can communicate with any device with an RS485 interface. In this 
configuration the MEGA-BAS card is a passive bridge which implements only the hardware levels 
required by the RS485 protocol. To use this configuration, you need to tell the local processor to release 
control of the RS485 bus: 
~$ megabas [0] wcfgmb 0 0 0 0 
If jumpers are removed, the card operates as MODBUS slave and implements the MODBUS RTU 
protocol. Any MODBUS master can access all the card's inputs, and set all the outputs using standard 
MODBUS commands. A detailed list of commands implemented can be found on GitHub:

**Comment by nikke344** [comment]
If jumpers are installed, Raspberry Pi can communicate with any device with an RS485 interface. In this 
configuration the MEGA-BAS card is a passive bridge which implements only the hardware levels 
required by the RS485 protocol. To use this configuration, you need to tell the local processor to release 
control of the RS485 bus: 
~$ megabas [0] wcfgmb 0 0 0 0 
If jumpers are removed, the card operates as MODBUS slave and implements the MODBUS RTU 
protocol. Any MODBUS master can access all the card's inputs, and set all the outputs using standard 
MODBUS commands. A detailed list of commands implemented can be found on GitHub:

**Comment by nikke344** [comment]
That command to release dont work

**Comment by alexburcea2877** [comment]
We have some errors in the manual
The command for release the bus is : megabas 0 rs485wr 0 9600 1 0 1
type "megabas -h rs485wr" for more info
