### ISSUE TITLE
Triac Node in Node Red Library will not allow you to specify any Triac Number other than 1

### ISSUE THREAD

**Issue by Kylem1122EIQ** [SequentMicrosystems/megabas-rpi#4]
The Triac Number selector does not appear to work, it allows you to change the number, but hitting "Done" and exiting the edit mode will not save the changes to the selector.

![image](https://user-images.githubusercontent.com/42618915/101548778-76642500-397a-11eb-819b-de4d56d1fe23.png)

![image](https://user-images.githubusercontent.com/42618915/101548817-8d0a7c00-397a-11eb-81d1-c550f29a5697.png)

**Comment by alexburcea2877** [comment]
Hi,
The bug has been solved.
Please update the repository and reinstall the nodes.
Thank you for supporting our products.
